config/routes.rb
Rails.application.routes.draw do
  root   "users#new"
  get    "/signup", to: "users#new"
  post  "/signup",  to: "users#create"
  get    "/login",  to: "sessions#new"
  post   "/login",  to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users
  resources :teams
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :team_members, dependent: :destroy
  has_many :users, through: :team_members

  validates :name, presence: true
end

app/models/team_member.rb
class TeamMember < ApplicationRecord
  belongs_to :user
  belongs_to :team
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :team_members, dependent: :destroy
  has_many :teams, through: :team_members

  validates :name,     presence: true
  validates :email,    presence: true
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  def require_login
    unless logged_in?
      flash[:warning] = "ログインしてください。"
      redirect_to login_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      reset_session
      log_in user
      flash[:success] = "ログインしました。"
      redirect_to user
    else
      flash.now[:danger] = "ログインできませんでした。"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    log_out
    flash[:success] = "ログアウトしました。"
    redirect_to root_path, status: :see_other
  end
end

app/controllers/team_members_controller.rb
class TeamMembersController < ApplicationController
  before_action :require_login

  def create
    team = Team.find(params[id])
    team_member = current_user.TeamMember.build(team_id: team.id)
    if team_member.save
      flash[:success] = "チームに参加しました。"
      redirect_to team_path(team)
    else
      flash.now[:danger] = "チームに参加できませんでした。"
      render team_path(team)
    end
  end

  def destroy
    
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :require_login

  def new
    @team = Team.new
  end

  def create
    @team = Team.new(team_params)
    if @team.save
      flash[:success] = "チームを作成しました。"
      redirect_to @team
    else
      flash.now[:danger] = "チームを作成できませんでした。"
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @team = Team.find(params[:id])
  end

  private

    def team_params
      params.require(:team).permit(:name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:show]
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      reset_session
      log_in @user
      flash[:success] = "ようこそ！"
      redirect_to @user
    else
      flash.now[:danger] = "登録できませんでした。"
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    reset_session
    @current_user = nil
  end
end

app/helpers/team_members_helper.rb
module TeamMembersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeamCollaborationApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/flash_messages" %>
    <%= render "shared/header" %>
    <div class="container mt-5">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_header.html.erb
<header class="p-3 border-bottom bg-white">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li><%= link_to "ホーム", root_path, class: "nav-link px-2 text-secondary" %></li>
      </ul>

      <div class="text-end">
        <% if logged_in? %>
          <%= link_to "プロフィール", current_user, class: "btn btn-info" %>
          <%= link_to "ログアウト", logout_path, data: { turbo_method: :delete }, class: "btn btn-danger" %>
        <% else %>
          <%= link_to "ログイン", login_path, class: "btn btn-info" %>
          <%= link_to "新規登録", signup_path, class: "btn btn-warning" %>
        <% end %>
      </div>
    </div>
  </div>
</header>

app/views/users/new.html.erb
<h2 class="text-center">新規登録</h2>

<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <%= form_with(model: @user, url: signup_path, local: true) do |f| %>

        <div class="mb-3">
          <%= f.label :name, "お名前", class: "form-label" %>
          <%= f.text_field :name, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= f.label :email, "メールアドレス", class: "form-label" %>
          <%= f.email_field :email, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= f.label :password, "パスワード", class: "form-label" %>
          <%= f.password_field :password, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= f.label :password_confirmation, "パスワード再確認", class: "form-label" %>
          <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>

        <div class="text-center">
          <%= f.submit "登録", class: "btn btn-outline-success" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="row justify-content-center">
  <div class="col-md-6">
    <div class="card shadow-sm">
      <div class="card-header text-center">
        <h4>ユーザー情報</h4>
      </div>
      <div class="card-body">
        <p><strong>お名前:</strong> <%= @user.name %></p>
        <p><strong>メールアドレス:</strong> <%= @user.email %></p>
      </div>
      <div class="card-footer text-center">
        <%= link_to "編集", "#", class: "btn btn-outline-primary btn-sm" %>
      </div>
    </div>
  </div>
</div>